spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jwt_security
    username: "admin"
    password: "1234567"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect